```{r eval=FALSE, include=FALSE}

setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("3_high_VS_3_low", "peel", c(7:15,19:27), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_3_high.3_low", "peel", c(7:15,19:30), group.A = 28:30)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_4115", "peel", c(16:18,28:30), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_high", "peel", c(19:30), group.A = 28:30)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_low_without_4115", "peel", c(7:15,28:30), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("all_high_VS_low", "peel", c(1:30), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("no_parents_high_VS_low", "peel", c(7:30), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("parents_160_VS_100", "peel", c(1:6), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55.497_VS_513.469", "peel", c(7:12,22:24,28:30), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("497_VS_513.469", "peel", c(7:12,22:24), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("4108.469_VS_497.57", "peel", c(10:15,22:27), group.A = c(10:12,25:27))
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("497_VS_4108.469", "peel", c(10:12,22:27), group.A = 22:24)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("487.4108_VS_all", "peel", c(7:30), group.A = c(19:21,25:27))
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
deseq_fc("high_VS_parents", "peel", c(1:6,19:30), group.A = 19:30)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
deseq_fc("low_VS_parents", "peel", c(1:18), group.A = 7:18)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
deseq_fc("parents_VS_low", "peel", c(1:18), group.A = 1:6)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
deseq_fc("4_high_VS_4_low", "peel", c(7:30), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
deseq_fc("high_VS_high_parent", "peel", c(4:6,19:30), group.A = 19:30)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
deseq_fc("low_VS_low_parent", "peel", c(1:3,7:18), group.A = 7:18)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
deseq_fc("low_parent_VS_low", "peel", c(1:3,7:18), group.A = 1:3)
rm(deseq_fc)


######################################################################


setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("BanG.101_VS_DanA", "clone", c(4,6,13:15,17:20), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("BanG.101_VS_DanA.116", "clone", c(4,6:9,13:15,17:20), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("BanG_VS_DanA", "clone", c(13:15,17:20), "high", "low")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("BanG_VS_DanA.116", "clone", c(7:9,13:15,17:20), "high", "low")

 
######################################################################

 
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("MYB6_VS_EV", "transgenic", c(1:10), "MYB6", "EV")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("bHLH94_VS_EV", "transgenic", c(1:5,16:20), "bHLH94", "EV")
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("MYB8b_VS_EV", "transgenic", c(1:5,11:15), "MYB8b", "EV")
rm(deseq_fc)

setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("high_exp_MYB6_VS_EV", "transgenic", c(1:3,5:7), "MYB6", "EV",PCA.id.labels = T)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("high_exp_bHLH94_VS_EV", "transgenic", c(1:3,5,17,18,20), "bHLH94", "EV",PCA.id.labels = T)
rm(deseq_fc)
```
``` {r}
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("bHLH94-like_VS_EV", "transgenic", c(1:5,16:18,20), "bHLH94", "EV",PCA.id.labels = T)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("by_PCA_MYB6_VS_EV", "transgenic", c(1:3,5:9), "MYB6", "EV",PCA.id.labels = T)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("by_PCA_bHLH94_VS_EV", "transgenic", c(1,3,5,16:20), "bHLH94", "EV",PCA.id.labels = T)
rm(deseq_fc)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("by_PCA_MYb8b_VS_EV", "transgenic", c(1,3,5,12,13), "MYB8b", "EV",PCA.id.labels = T)
rm(deseq_fc)
#```
#```{r eval=FALSE, include=FALSE}

####### venn ##############
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","3_high_VS_3_low","55_VS_4115","55_VS_high",merge.file.number = "1")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","parents_160_VS_100","3_high_VS_3_low","55_VS_4115",merge.file.number = "2")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","parents_160_VS_100","55_VS_3_high.3_low",merge.file.number = "3")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","55_VS_high","55_VS_low_without_4115","55_VS_4115",merge.file.number = "4")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","no_parents_high_VS_low","parents_160_VS_100","55_VS_3_high.3_low","55_VS_low_without_4115",merge.file.number = "5")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","3_high_VS_3_low","55_VS_4115",merge.file.number = "6")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
venn.di("peel","up","high_VS_parents","parents_VS_low","4_high_VS_4_low",merge.file.number = "7")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
venn.di("peel","up","high_VS_high_parent","low_VS_low_parent","4_high_VS_4_low",merge.file.number = "8")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
venn.di("peel","up","high_VS_high_parent","low_parent_VS_low","4_high_VS_4_low",merge.file.number = "9")
rm(venn.di)

#########

setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("clone","up","BanG.101_VS_DanA.116","BanG.101_VS_DanA","BanG_VS_DanA",merge.file.number = "1")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("clone","up","BanG.101_VS_DanA.116","BanG_VS_DanA",merge.file.number = "2")
rm(venn.di)
setwd("P:/yonatan/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("clone","up","BanG.101_VS_DanA.116","BanG.101_VS_DanA","BanG_VS_DanA.116","BanG_VS_DanA",merge.file.number = "3")
rm(venn.di)


```
