```{r eval=FALSE, include=FALSE}

setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("3_high_VS_3_low", "peel", c(7:15,19:27), "high", "low")
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_3_high.3_low", "peel", c(7:15,19:30), group.A = 28:30)
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_4115", "peel", c(16:18,28:30), "high", "low")
rm(deseq_fc)
```
```{r eval=FALSE, include=FALSE}
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_high", "peel", c(19:30), group.A = 28:30)
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55_VS_low_without_4115", "peel", c(7:15,28:30), "high", "low")
rm(deseq_fc)
```
```{r}
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("all_high_VS_low", "peel", c(1:30), "high", "low")
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("no_parents_high_VS_low", "peel", c(7:30), "high", "low")
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("parents_160_VS_100", "peel", c(1:6), "high", "low")
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("55.497_VS_513.469", "peel", c(7:12,22:24,28:30), "high", "low")
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("497_VS_513.469", "peel", c(7:12,22:24), "high", "low")
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("4108.469_VS_497.57", "peel", c(10:15,22:27), group.A = c(10:12,25:27))
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("497_VS_4108.469", "peel", c(10:12,22:27), group.A = 22:24)
rm(deseq_fc)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("DEseq.FC.with.plots.and.GO.280322.R")
 deseq_fc("487.4108_VS_all", "peel", c(7:30), group.A = c(19:21,25:27))
rm(deseq_fc)
######################################################################


####### venn ##############

setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","3_high_VS_3_low","55_VS_4115","55_VS_high",merge.file.number = "1")
rm(venn.di)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","parents_160_VS_100","3_high_VS_3_low","55_VS_4115",merge.file.number = "2")
rm(venn.di)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","parents_160_VS_100","55_VS_3_high.3_low",merge.file.number = "3")
rm(venn.di)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","55_VS_high","55_VS_low_without_4115","55_VS_4115",merge.file.number = "4")
rm(venn.di)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","no_parents_high_VS_low","parents_160_VS_100","55_VS_3_high.3_low","55_VS_low_without_4115",merge.file.number = "5")
rm(venn.di)
setwd("C:/Users/yonye/OneDrive/שולחן העבודה/מעבדה/RNAseq_yonatan_2021/DESeq2")
source("merge.file_venn.diagramm.270322.R")
 venn.di("peel","up","3_high_VS_3_low","55_VS_4115",merge.file.number = "6")
rm(venn.di)

```
